import importlib
import re
import tempfile
import unittest
from pathlib import Path


EXPECTED_COLORS = {
    'M0': '#D55E00',
    'M1': '#8C9AA9',
    'M2': '#A7B6C2',
    'M3': '#6B8DB5',
    'M4': '#E69F00',
    'M5': '#F0C04A',
    'M6': '#7CB342',
    'M7': '#56B4E9',
    'M8': '#CC79A7',
    'M9': '#0072B2',
    'M9_RF2': '#009E73',
}


class TestModelPalette(unittest.TestCase):
    def load_palette(self):
        return importlib.import_module('tools.analysis.model_palette')

    def test_canonical_palette_matches_approved_existing_colors(self):
        palette = self.load_palette()

        self.assertEqual(palette.MODEL_COLORS, EXPECTED_COLORS)
        self.assertEqual(set(palette.MODEL_MARKERS), set(EXPECTED_COLORS))
        self.assertEqual(set(palette.MODEL_LINESTYLES), set(EXPECTED_COLORS))

    def test_flow_styles_use_model_families_and_neutral_fw2_controls(self):
        palette = self.load_palette()
        styles = palette.FLOW_SETTING_STYLES

        self.assertEqual(styles['M6']['color'], EXPECTED_COLORS['M6'])
        self.assertEqual(styles['M9_no_flow']['color'], EXPECTED_COLORS['M9'])
        self.assertEqual(styles['M9_no_flow']['fillstyle'], 'none')
        self.assertEqual(styles['M9']['color'], EXPECTED_COLORS['M9'])
        self.assertEqual(styles['M9_RF2']['color'], EXPECTED_COLORS['M9_RF2'])
        self.assertEqual(styles['M9_RF2']['marker'], 'D')
        self.assertEqual(styles['T_FW2_20e_RF2']['color'], palette.SUPPLEMENTAL_NEUTRAL)
        self.assertEqual(styles['T_FW2_20e_RF4']['color'], palette.SUPPLEMENTAL_NEUTRAL)
        self.assertNotEqual(
            styles['T_FW2_20e_RF2']['marker'],
            styles['T_FW2_20e_RF4']['marker'])

    def test_latex_generation_is_deterministic_and_matches_python_hex(self):
        palette = self.load_palette()
        with tempfile.TemporaryDirectory() as temp_dir:
            first = Path(temp_dir) / 'first.tex'
            second = Path(temp_dir) / 'second.tex'
            palette.write_latex_palette(first)
            palette.write_latex_palette(second)

            first_text = first.read_text(encoding='ascii')
            second_text = second.read_text(encoding='ascii')

        self.assertEqual(first_text, second_text)
        self.assertIn('Generated by tools/analysis/model_palette.py', first_text)
        self.assertIn(r'\newcommand{\modelid}', first_text)
        definitions = dict(re.findall(
            r'\\definecolor\{([^}]+)\}\{HTML\}\{([0-9A-F]{6})\}',
            first_text))
        self.assertEqual(len(definitions), len(EXPECTED_COLORS) + 1)
        for model_id, hex_color in EXPECTED_COLORS.items():
            self.assertEqual(
                definitions[palette.LATEX_COLOR_NAMES[model_id]],
                hex_color.removeprefix('#'))
        self.assertEqual(
            definitions['supplementalNeutral'],
            palette.SUPPLEMENTAL_NEUTRAL.removeprefix('#'))

    def test_unknown_model_color_fails_clearly(self):
        palette = self.load_palette()

        with self.assertRaisesRegex(KeyError, 'Unknown model ID'):
            palette.get_model_color('M10')

    def test_main_variant_data_does_not_embed_colors(self):
        figures = importlib.import_module('tools.analysis.plot_full_paper_figures')

        self.assertTrue(all(len(row) == 5 for row in figures.VARIANTS))

    def test_model_hex_literals_exist_only_in_canonical_palette_module(self):
        root = Path(__file__).resolve().parents[1]
        script_paths = [
            root / 'tools/analysis/plot_full_paper_figures.py',
            root / 'tools/analysis/plot_full_ablation_paper_assets.py',
            root / 'tools/analysis/plot_proposal_ablation_figures.py',
            root / 'tools/analysis/render_qualitative_figure.py',
        ]
        for script_path in script_paths:
            source = script_path.read_text(encoding='utf-8').upper()
            for model_id, hex_color in EXPECTED_COLORS.items():
                self.assertNotIn(
                    hex_color.upper(),
                    source,
                    f'{script_path.name} duplicates {model_id} color')


if __name__ == '__main__':
    unittest.main()
