#!/usr/bin/env python
"""Canonical model-identity colors and redundant plot styles."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LATEX_OUTPUT = (
    PROJECT_ROOT / 'paper_assets' / 'manuscript_latex' /
    'resfes2026_witidar' / 'tables' / 'model_palette.tex')

MODEL_COLORS = {
    'M0': '#D55E00',
    'M1': '#8C9AA9',
    'M2': '#A7B6C2',
    'M3': '#6B8DB5',
    'M4': '#E69F00',
    'M5': '#F0C04A',
    'M6': '#7CB342',
    'M7': '#56B4E9',
    'M8': '#CC79A7',
    'M9': '#0072B2',
    'M9_RF2': '#009E73',
}

MODEL_MARKERS = {
    'M0': 'o',
    'M1': 's',
    'M2': '^',
    'M3': 'v',
    'M4': 'D',
    'M5': 'P',
    'M6': 'X',
    'M7': '<',
    'M8': '>',
    'M9': 'h',
    'M9_RF2': '*',
}

MODEL_LINESTYLES = {
    'M0': '-',
    'M1': '--',
    'M2': '-.',
    'M3': ':',
    'M4': '-',
    'M5': '--',
    'M6': '-.',
    'M7': ':',
    'M8': '-',
    'M9': '--',
    'M9_RF2': '-',
}

LATEX_COLOR_NAMES = {
    model_id: f"model{model_id.replace('_', '')}"
    for model_id in MODEL_COLORS
}

SUPPLEMENTAL_NEUTRAL = '#6B7C93'

FLOW_SETTING_STYLES = {
    'M6': {
        'color': MODEL_COLORS['M6'],
        'marker': 'o',
        'fillstyle': 'full',
    },
    'M9_no_flow': {
        'color': MODEL_COLORS['M9'],
        'marker': 'o',
        'fillstyle': 'none',
    },
    'M9': {
        'color': MODEL_COLORS['M9'],
        'marker': 'o',
        'fillstyle': 'full',
    },
    'M9_RF2': {
        'color': MODEL_COLORS['M9_RF2'],
        'marker': 'D',
        'fillstyle': 'full',
    },
    'T_FW2_20e_RF2': {
        'color': SUPPLEMENTAL_NEUTRAL,
        'marker': 's',
        'fillstyle': 'full',
    },
    'T_FW2_20e_RF4': {
        'color': SUPPLEMENTAL_NEUTRAL,
        'marker': '^',
        'fillstyle': 'full',
    },
}


def get_model_color(model_id):
    try:
        return MODEL_COLORS[model_id]
    except KeyError as exc:
        raise KeyError(f'Unknown model ID: {model_id}') from exc


def render_latex_palette():
    lines = [
        '% Generated by tools/analysis/model_palette.py. Do not edit manually.',
    ]
    for model_id, hex_color in MODEL_COLORS.items():
        lines.append(
            f"\\definecolor{{{LATEX_COLOR_NAMES[model_id]}}}"
            f"{{HTML}}{{{hex_color.removeprefix('#')}}}")
    lines.append(
        f"\\definecolor{{supplementalNeutral}}{{HTML}}"
        f"{{{SUPPLEMENTAL_NEUTRAL.removeprefix('#')}}}")
    lines.extend([
        r'\newcommand{\modelid}[2]{%',
        r'  \raisebox{0.15ex}{\textcolor{#1}{\rule{0.85ex}{0.85ex}}}\nobreakspace\textbf{#2}%',
        r'}',
        '',
    ])
    return '\n'.join(lines)


def write_latex_palette(output_path=DEFAULT_LATEX_OUTPUT):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_latex_palette(), encoding='ascii')
    return output_path


if __name__ == '__main__':
    print(write_latex_palette())
